### PR TITLE
Seccomp notifier backport to 5.8

### PR DESCRIPTION
**Pull request by solarkennedy**
Just pushing this up in case I git-screwup.

This is my first time backporting something in the linux kernel.

Currently debugging `make TARGETS="seccomp" kselftest`.

### CODE REVIEW

**Comment by sargun** [comment]
@solarkennedy You might need to pickup this patch as well: https://lkml.org/lkml/2020/8/7/699

**Comment by sargun** [comment]
this commit: https://git.kernel.org/pub/scm/linux/kernel/git/kees/linux.git/commit/?h=for-next/seccomp -- you should just be able to cherry-pick it out of @kees tree

**Comment by solarkennedy** [comment]
> this commit: https://git.kernel.org/pub/scm/linux/kernel/git/kees/linux.git/commit/?h=for-next/seccomp -- you should just be able to cherry-pick it out of @kees tree

Got that one. There were also significant changes to file.c, it looked cleaner to merge in the whole close-range-5.9 that contained them, but that may have been overkill.

**Comment by sargun** [comment]
Oh, yeah, close-range has some cool stuff in it too.

**Review by sargun — APPROVED** [review]

**Comment by sargun** [comment]
I think that this will also generate new libc headers that you'll have to figure out how to build / install.

**Comment by solarkennedy** [comment]
Got it. Using the local headers the self tests pass. I'll merge this in and continue working on my branch if I need to, but otherwise I think this will make a kernel we can actually start using!

**Comment by sargun** [comment]
@solarkennedy A buildkite build for this would be kinda fun, cool, and neat. Our configs aren't secret or proprietary.

**Pull request merged**
